services:
  - type: web
    name: veteranai-final-test
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app --bind 0.0.0.0:$PORT --timeout 60
    envVars:
      - key: PYTHON_VERSION
        value: "3.11"
    autoDeploy: true