services:
  - type: web
    name: veteran-ai-premium
    runtime: python
    region: oregon
    plan: free
    
    buildCommand: pip install -r requirements_production.txt
    startCommand: python production_secure_main.py
    
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.7
      - key: FLASK_ENV
        value: production
      - key: FLASK_DEBUG
        value: False
      - key: SECRET_KEY
        generateValue: true
      - key: DATABASE_URL
        value: sqlite:///production.db
      - key: HOST
        value: 0.0.0.0
      - key: PORT
        value: 10000
    
    autoDeploy: true