services:
  - type: web
    name: veteran-ai-test-deploy
    runtime: python
    region: oregon
    plan: free
    
    buildCommand: pip install flask
    startCommand: python app.py
    
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.7
    
    autoDeploy: true