services:
  - type: web
    name: dify-rag002
    runtime: python
    region: oregon
    plan: free
    
    buildCommand: pip install -r requirements_production.txt
    startCommand: python production_secure_main.py
    
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.7
      - key: FLASK_ENV
        value: production
      - key: SECRET_KEY
        generateValue: true
      - key: DATABASE_URL
        value: sqlite:///production.db
    
    autoDeploy: true