services:
  - type: web
    name: dify-rag002
    env: python
    pythonVersion: "3.11.7"
    buildCommand: "pip install -r requirements.txt"
    startCommand: "gunicorn app:app"
    healthCheckPath: "/"
